server:
  port: 9009

spring:
  application:
    name: tensquare-sms
  redis:
    host: 192.168.31.129
    port: 6379
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.31.129
    port: 5672

# https://cloud.tencent.com/document/product/382/13613
tencent:
  sms:
    appid: 1400
    appkey: d687e14
    templateid: 286
    smssign: 腾讯云


