server:
  port: 9003

spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.128:3306/tensquare_qa?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql

jwt:
  config:
    key: tensquare