eureka:
  client:
    fetch-registry: true # Eureka显示自己的信息
    register-with-eureka: true # Eureka也注册到Eureka上
    registry-fetch-interval-seconds: 10 # 当前eureka client每隔10s就去注册中心获取一次最新注册资讯，默认30s
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 10 # 超过10s，没有收到客户端的心跳，就将其除去，默认90s
    lease-renewal-interval-in-seconds: 5 # 客户端每隔5秒先服务端发送一次心跳
    prefer-ip-address: true # 使用IP代替主机名在注册中心做唯一标识
    metadata-map:
      version: ${info.version}


jwt:
  config:
    key: tensquare

server:
  port: 9011
spring:
  application:
    name: cloud-zuul
zuul:
  sensitive-headers: true # 全局自定义敏感头
  routes:
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user




ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OKToRetryOnAllOperations: false
  ServerListRefreshInterval: 3


hystrix:
  command:
    tensquare-base:
      circuitBreaker:
        errorThresholdPercentage: 50
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
