server:
  port: 9002

spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.128:3306/tensquare_recruit?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql