server:
  port: 9008

spring:
  application:
    name: tensquare-user
  datasource:
    url: jdbc:mysql://192.168.31.129:3306/tensquare_user?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.31.129
    port: 6379
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.31.129
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  config:
    key: tensquare
    ttl: 3600000 # 默认token一小时才过期


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"