server:
  port: 9008

spring:
  application:
    name: tensquare-user
  datasource:
    url: jdbc:mysql://192.168.31.128:3306/tensquare_user?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.31.128
    port: 6379
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.31.128
    port: 5672