server:
  port: 9005

spring:
  application:
    name: tensquare-gathering
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.129:3306/tensquare_gathering?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql

jwt:
  config:
    key: tensquare